### ISSUE TITLE
douyin-clear-php/apis.txt 这里面的所有接口都没法使用了

### ISSUE THREAD

**Issue by 13551527194** [zbfzn/douyin-clear-php#11]
您好，请问您知道为啥，douyin-clear-php/apis.txt 这里面的所有接口都没法使用了么，能通过哪儿获取呢

**Comment by zbfzn** [comment]
> 您好，请问您知道为啥，douyin-clear-php/apis.txt 这里面的所有接口都没法使用了么，能通过哪儿获取呢

可以参考https://github.com/zbfzn/douyin-clear-php/issues/5
