### ISSUE TITLE
抖音列表

### ISSUE THREAD

**Issue by 13551527194** [zbfzn/douyin-clear-php#13]
我用Fiddler4抓取分析用户列表的时候，能得到所有的视频信息，但是自己请求的时候，总是：'{"status_code": 0, "has_more": 0, "max_cursor": 0, "min_cursor": 0, "aweme_list": []}' ，想动手做一个和你这个接口一样的东西 /plugins/douyin/userPrase/get_douyin.php
，想请问你是如何实现的呢，我是缺少了什么其它信息么，我发现Fiddler里面可以重复执行是没问题的，求教

**Comment by zbfzn** [comment]
用户列表解析不再本项目范围，请理解。

**Comment by 13551527194** [comment]
其实我已经解析出来了，不过总是遇到有时能拿到列表，有时拿不到列表的尴尬事儿


 
---原始邮件---
发件人: "zbfzn"<notifications@github.com>
发送时间: 2019年6月29日 18:22:34
收件人: "zbfzn/douyin-clear-php"<douyin-clear-php@noreply.github.com>;
抄送: "Author"<author@noreply.github.com>;"13551527194"<1620829248@qq.com>;
主题: Re: [zbfzn/douyin-clear-php] 抖音列表 (#13)



用户列表解析不再本项目范围，请理解。
