### ISSUE TITLE
对项目进行了封装，并推送给作者了

### ISSUE THREAD

**Issue by lvyac** [zbfzn/douyin-clear-php#17]
项目地址 https://github.com/lvyac/douyin-clear-php     2019/7/9 亲测可用

**Comment by yy755964539** [comment]
![image](https://user-images.githubusercontent.com/33890981/60885694-bd7c5100-a282-11e9-805f-b9a8d80ad6a1.png)
![image](https://user-images.githubusercontent.com/33890981/60885706-c4a35f00-a282-11e9-8ac7-c267f5980704.png)
好像不行...

**Comment by lvyac** [comment]
可以的我下午亲测，你要先按F12摸拟成手机，再复制网址过去，或复制网址到手机上查看
