### ISSUE TITLE
大佬，不行啊，提示链接不正确

### ISSUE THREAD

**Issue by wpneu** [zbfzn/douyin-clear-php#18]
执行：
http://localhost:63343/douyin/douyin-video.php?url=http://v.douyin.com/kHQpWj/&isFormat=1&old=0
然后报错：
{"status":false,"errorMes":"链接不正确"}

换了好几个链接都不行。

**Comment by wpneu** [comment]
用你昨天的链接也不行
![image](https://user-images.githubusercontent.com/22270447/60939542-a41ee780-a30a-11e9-82b3-45ed5d5928c1.png)

**Comment by wpneu** [comment]
用你昨天的链接还是不行
![image](https://user-images.githubusercontent.com/22270447/60939746-69697f00-a30b-11e9-88e2-88fc1611e396.png)

**Comment by zbfzn** [comment]
等我回去看看哈，电脑不在身边

**Comment by zbfzn** [comment]
> 执行：
> http://localhost:63343/douyin/douyin-video.php?url=http://v.douyin.com/kHQpWj/&isFormat=1&old=0
> 然后报错：
> {"status":false,"errorMes":"链接不正确"}
> 
> 换了好几个链接都不行。

你这个链接是个人主页，本来就不行，我的不行是iid和device_id被封，导致不能请求到数据。我已经新加了一个设备参数应该可以用一段时间。
