### ISSUE TITLE
你好，请问douyinDevice这个文件里面是什么意思

### ISSUE THREAD

**Issue by ChinaBygones** [zbfzn/douyin-clear-php#20]
你好，请问douyinDevice这个文件里面是什么意思，

还有我刚才测试了一下获取不到视频链接

**Comment by zbfzn** [comment]
我刚刚测试正常啊

**Comment by ChinaBygones** [comment]
> 我刚刚测试正常啊

我测试就403或者拒绝访问之类的

**Comment by zbfzn** [comment]
放在手机上是正常的，电脑可能不能用https://api.amemv.com/aweme/v1/play/?video_id=v0300ffb0000biabmhqhh3mrpo38d760&line=1&ratio=540p&media_type=4&vr_type=0&improve_bitrate=0&is_play_url=1

**Comment by ChinaBygones** [comment]
> 放在手机上是正常的，电脑可能不能用https://api.amemv.com/aweme/v1/play/?video_id=v0300ffb0000biabmhqhh3mrpo38d760&line=1&ratio=540p&media_type=4&vr_type=0&improve_bitrate=0&is_play_url=1

手机也不行，你那边可以访问吗

**Comment by zbfzn** [comment]
可以
