### ISSUE TITLE
大神请问一下，无水印视频怎么获取，拿到的都是有水印的

### ISSUE THREAD

**Issue by hshy** [zbfzn/douyin-clear-php#22]
大神请问一下，如何提供iid和device_id给你

**Comment by zbfzn** [comment]
我这个接口获取的就是无水印的

**Comment by zbfzn** [comment]
> 大神请问一下，如何提供iid和device_id给你

http://lyfzn.top/api/douyinApi/uploadDevice.php?iid=值&device_id=值&user_name=GitHub用户名
