### ISSUE TITLE
关于作者信息

### ISSUE THREAD

**Issue by lvxianchao** [zbfzn/douyin-clear-php#24]
想问下作者有办法能拿到作者详情信息吗？或者视频详情信息

**Comment by zbfzn** [comment]
> 想问下作者有办法能拿到作者详情信息吗？或者视频详情信息

比如哪些信息？

**Comment by zbfzn** [comment]
> 想问下作者有办法能拿到作者详情信息吗？或者视频详情信息

如果需要完整信息，添加参数 isFormat=0,即可获取原始数据

**Comment by lvxianchao** [comment]
@zbfzn 比如作者的 unique_id, videos_count, followers_count, favorite_count 这些；我看到网页版的那种都是经过处理的，目前还不知道怎么处理回去，而且信息也不是很全
