### ISSUE TITLE
老哥 你这个还没有修改

### ISSUE THREAD

**Issue by 5wcx** [zbfzn/douyin-clear-php#26]
https://lyfzn.top/api/douyinApi/?url=http://v.douyin.com/ABErWB/
urls还是返回空

**Comment by zbfzn** [comment]
嗯，😂服务器没同步的

**Comment by zbfzn** [comment]
> https://lyfzn.top/api/douyinApi/?url=http://v.douyin.com/ABErWB/
> urls还是返回空

服务器已同步
