### ISSUE TITLE
你好 突然失效了

### ISSUE THREAD

**Issue by 5wcx** [zbfzn/douyin-clear-php#27]
抖音接口调用失败{680:[4][0][1][1]}{251:[4][0][1][1]}{140:[4][0][1][1]}
返回这个    应该怎么搞呢

**Comment by 5wcx** [comment]
成功率非常低，然后 分享的连接复制抖音打不开  难道是抖音出问题了？

**Comment by 5wcx** [comment]
https://aweme.snssdk.com/aweme/v1/aweme/detail/?origin_type=link&retry_type=no_retry&iid=74655440239&device_id=57318346369&ac=wifi&channel=update&aid=1128&app_name=aweme&version_code=680&version_name=6.8.0&device_platform=android&ssmix=a&device_type=MI+8&device_brand=xiaomi&language=zh&os_api=22&os_version=5.1.1&uuid=865166029463703&openudid=ec6d541a2f7350cd&manifest_version_code=680&resolution=1080*1920&dpi=480&update_version_code=2512&ts=1561136204&as=a1e500706c54fd8c8d&cp=004ad55fc8d60ac4e1&aweme_id=6710893995377167628   比如这个连接 刷新50次 估计成功1次。抖音在改动  网页版的没有水印了。

**Comment by zbfzn** [comment]
嗯，再搞一搞

**Comment by zbfzn** [comment]
已解决
