### ISSUE TITLE
小哥 可以出个教程吗。我抓包了没有这种连接啊 连接是哪来的？其他参数都不用变吗？ cookie不会失效吗？

### ISSUE THREAD

**Issue by 5wcx** [zbfzn/douyin-clear-php#5]

**Comment by zbfzn** [comment]
cookie有效性正在测试，教程空闲时间写吧

**Comment by 5wcx** [comment]
捂脸..cookie好像失效了..请问是用的抓包还是hook 还是什么技术？

**Comment by zbfzn** [comment]
抓包，经测试使用登陆后的cookie还未失效，你可以抓登录后的cookie使用。工具：fiddler

**Comment by 5wcx** [comment]
我会的。我安卓 苹果都抓了 都没有 api-hl.amemv.com这个地址 。难道是版本的问题吗？测试 cookie删掉也能获取到。早上有一段时间 用你的cookie我这边就获取不到  你的域名可以。下午我这边又可以了。。。。好神奇。

**Comment by fantasybei** [comment]
同求，老哥简单说下拿到itemId后，是怎么抓包知道要请求这个$api="https://api-hl.amemv.com/aweme/v1/aweme/detail/.....，的吗？谢谢。

**Comment by zbfzn** [comment]
每次打开APP，抖音视频都会检测剪切板的视频分享链接。利用这个原理，从其他地方复制一段分享口令如：#在抖音，记录美好生活##slomo 我见过天使，遇过魔鬼，亲爱的，你到底是谁？#来自天堂的魔鬼 http://v.douyin.com/***/ 复制此链接，打开【抖音短视频】，直接观看视频！  这时我们再次重新进入APP，它会弹出分享内容，这时就可以点击“打开看看”，就抓到对应接口了

**Comment by fantasybei** [comment]
> 每次打开APP，抖音视频都会检测剪切板的视频分享链接。利用这个原理，从其他地方复制一段分享口令如：#在抖音，记录美好生活##slomo 我见过天使，遇过魔鬼，亲爱的，你到底是谁？#来自天堂的魔鬼 http://v.douyin.com/***/ 复制此链接，打开【抖音短视频】，直接观看视频！ 这时我们再次重新进入APP，它会弹出分享内容，这时就可以点击“打开看看”，就抓到对应接口了

可以抓到了，谢谢

**Comment by zbfzn** [comment]
喜欢可以给个star支持下哦⊙∀⊙！

**Comment by CHEN-HONGLIN** [comment]
不谢https://www.fdlzf.com/douyin/

**Comment by CHEN-HONGLIN** [comment]
> 同求，老哥简单说下拿到itemId后，是怎么抓包知道要请求这个$api="[https://api-hl.amemv.com/aweme/v1/aweme/detail/.....，的吗？谢谢。](https://api-hl.amemv.com/aweme/v1/aweme/detail/.....%EF%BC%8C%E7%9A%84%E5%90%97%EF%BC%9F%E8%B0%A2%E8%B0%A2%E3%80%82)

不谢哦https://www.fdlzf.com/douyin/
